# Generated by Django 4.1.3 on 2023-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.CharField(default='Пусто', max_length=256),
        ),
    ]
