# Generated by Django 4.1.3 on 2023-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
