# Generated by Django 4.1.3 on 2023-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users_list',
        ),
        migrations.AddField(
            model_name='project',
            name='users_list',
            field=models.ManyToManyField(to='TODO.user'),
        ),
    ]
